const motsClasses2 = {
    "A":"couleur1",
    "B":"couleur2",
    "C":"couleur3",
    "D":"couleur4",
    "Bleu":"couleur1",
    "Rouge":"couleur2",
    "Violet":"couleur3",
    "Jaune":"couleur4",
    "les côtés":"couleur4",
    "extrêmes":"couleur4",
    // "L'extrême":"couleur4",
    "Contradictions":"couleur4",
    "paradoxes":"couleur4",
    "pôles":"couleur3",
    "s'inverser":"couleur4",
    "convertir":"couleur3",
    "Positive":"couleur1",
    "Négative":"couleur2",
    "gentil":"couleur1",
    "méchant":"couleur2",
    "tôt":"couleur1",
    "tard":"couleur2",
    "tout":"couleur1",
    "rien":"couleur2",
    "ensembles":"couleur3",
    "extrême":"couleur4",
    "extrémités":"couleur4",
    "centre":"couleur3",
    "l'un":"couleur1",
    "l'autre":"couleur2",
    "variables":"couleur3",
    "compromis":"couleur3",
    "croisements":"couleur3",
    "Ordre":"couleur1",
    "Chaos":"couleur2",
    "anatomies":"couleur3",
    "binaires":"couleur3",
    "troisième":"couleur3",
    "métaphoriques":"couleur3",
    "dissonances":"couleur2",
    "consonnances":"couleur1",
    "cognitives":"couleur3",
    "Vesica piscis":"couleur3",
    "Acheter":"couleur1",
    "Vendre":"couleur2",
    "système":"couleur3",
    "Le nombre de la bête":"couleur3",
    "Vie":"couleur1",
    "Mort":"couleur2",
    // "Début":"couleur1",
    "Fin":"couleur2",
    "entrechoquer":"couleur3",
    "corruption":"couleur3",
    "Terre":"couleur3",
    "Noir":"couleur1",
    "Blanc":"couleur2",
    "Clestial":"couleur1",
    "Musepi":"couleur2",
    "contresens":"couleur4",
    "comportements":"couleur3",
    "contradictoire":"couleur3",
    "anatomie":"couleur3",
    "le bon grain":"couleur1",
    "et l'ivraie":"couleur2",
    "Plomb":"couleur1",
    "Or":"couleur2",
    "Source":"couleur1",
    "son contraire":"couleur2",
    "Nuance de gris":"couleur3",
    "Simultanément":"couleur3",
    "conception":"couleur3",
    "l'infiniment petit":"couleur1",
    "l'infiniment grand":"couleur2",
    "lointain passé":"couleur1",
    "lointain futur":"couleur2",
    "le criminel":"couleur3",
    "mort":"couleur2",
    "vie":"couleur1",
    "monde":"couleur3",
    "Église":"couleur3",
    "Pi":"couleur3",
    "transition":"couleur3",
    "Binarité":"couleur3",
    "topologie":"couleur3",
    "Triangle":"couleur3",
    "polarités":"couleur3",
    "tricorn":"couleur3",
    "la trinité":"couleur3",
    "Baptême":"couleur1",
    "1re communion":"couleur3",
    "Confirmation":"couleur2",
    "la culture française":"couleur3",
    "passées":"couleur2",
    "mémoire":"couleur3",
    "Guerre":"couleur3",
    "Trois":"couleur3",
    "l'endroit":"couleur1",
    "l'envers":"couleur2",
    "l'interaction":"couleur3",
    "guerres humaines":"couleur3",
    "le contraste":"couleur3",
    "L'entre-deux":"couleur3",
    "Triforce":"couleur3",
    "commun":"couleur3",
    "Volume":"couleur3",
    "triangles":"couleur3",
    "sommet":"couleur3",
    "étranglement":"couleur3",
    "milieu":"couleur3",
    "faible":"couleur1",
    "fort":"couleur2",
    "pauvre":"couleur1",
    "riche":"couleur2",
    "Espace et Temps":"couleur3",
    "assemblée":"couleur3",
    "réunion":"couleur3",
    "L'église ":"couleur3",
    "Univers":"couleur3",
    "Système":"couleur3",
    "Structure":"couleur3",
    "Une donnée":"couleur3",
    "accumulation":"couleur3",
    "Écosystème":"couleur3",
    // "une masse":"couleur3",
    "énergie":"couleur3",
    "sélection":"couleur3",
    "croisement":"couleur3",
    "gauche":"couleur1",
    "droite":"couleur2",
    "rayon":"couleur3",
    // "360°":"couleur4",
    "180°":"couleur3",
    "90°":"couleur3",
    // "60°":"couleur2",
    "30°":"couleur3",
    "Faible":"couleur1",
    "Fort":"couleur2",
    "Moins":"couleur1",
    "Plus":"couleur2",
    "Petit":"couleur1",
    "Grand":"couleur2",
    // "3":"couleur3",
    "complet":"couleur4",
    "Mais":"couleur3",
    "Froid":"couleur1",
    "Chaud":"couleur2",
    "moitié":"couleur3",
    "Bas":"couleur1",
    "Haut":"couleur2",
    "Mer":"couleur1",
    "Ciel":"couleur2",
    "hiérarchie":"couleur3",
    "Différences":"couleur3",
    "Distance":"couleur3",
    "Dualité":"couleur3",
    "Etats":"couleur3",
    "Tier-list":"couleur3",
    "Entre-deux":"couleur3",
    "Dieu":"couleur1",
    "Diable":"couleur2",
    "problématique":"couleur3",
    "problème":"couleur3",
    "Liberté":"couleur1",
    "Fraternité":"couleur2",
    "Égalité":"couleur3",
    "horizontal":"couleur1",
    "vertical":"couleur2",
    "Axe":"couleur3",
    "Rayons":"couleur3",
    "possibilités":"couleur3",
    "L'endroit":"couleur1",
    "L'envers":"couleur2",
    "l'entre-deux":"couleur3",
    "triangle":"couleur3",
    "moitiés":"couleur3",
    "intersection":"couleur3",
    "tri":"couleur3",
    "Tri":"couleur3",
    "angle":"couleur3",
    "côté":"couleur4",
    "pointe":"couleur3",
    "Adversaire":"couleur2",
    "opposé":"couleur2",
    "satan":"couleur2",
    "opposition":"couleur2",
    "Opposé":"couleur2",
    "=":"couleur3",
    "vrai":"couleur1",
    "faux":"couleur2",
    "potentiel":"couleur3",
    "espace":"couleur3",
    "Corne":"couleur3",
    "Pointe":"couleur3",
    "Trivium":"couleur3",
    "Entrée":"couleur1",
    "Sortie":"couleur2",
    "couleurs":"couleur3",
    "Le noir":"couleur1",
    "le noir":"couleur1",
    "Le blanc":"couleur2",
    "le blanc":"couleur2",
    "Bas":"couleur1",
    "Haut":"couleur2",
    "Lumière":"couleur2",
    "Ombre":"couleur1",
    "Moitié":"couleur3",
    "Centre":"couleur3",
    "Segment":"couleur3",
    "angles":"couleur3",
    "dent":"couleur3",
    "pointue":"couleur3",
    "absolue":"couleur3",
    "trident":"couleur3",
    "hasard":"couleur3",
    "Ichthus":"couleur3",
    "humain":"couleur3",
    "Pouvoir":"couleur3",
    "pouvoir":"couleur3",
    "survie":"couleur3",
    "groupe":"couleur3",
    "masse":"couleur3",
    "informations":"couleur3",
    "métaphores":"couleur3",
    "nombre":"couleur3",
    "transitions":"couleur3",
    "Si":"couleur3",
    "somme":"couleur3",
    "Début":"couleur1",
    "Origine":"couleur3",
    "Corps":"couleur3",
    "dimension":"couleur3",
    "Dimension":"couleur3",
    "Devant":"couleur1",
    "Derrière":"couleur2",
    "Représentation":"couleur3",
    // "bas":"couleur1",
    // "haut":"couleur2",
    // "corps":"couleur3",
    "fusion":"couleur3",
    "polarité":"couleur3",
    "blanche":"couleur1",
    "noire":"couleur2",
    "contraste":"couleur3",
    "avant":"couleur1",
    "arrière":"couleur2",
    "Postérieur":"couleur3",
    "Membres":"couleur3",
    "Épicentre":"couleur3",
    "abstrait":"couleur1",
    "abstraite":"couleur1",
    "concret":"couleur2",
    "concrète":"couleur2",
    "centrale":"couleur3",
    "La partie":"couleur3",
    "source":"couleur1",
    "éléments":"couleur3",
    "Le péché":"couleur3",
    "Assis":"couleur3",
    "jardin d'Éden":"couleur3",
    "En haut":"couleur1",
    "En bas":"couleur2",
    "personnes":"couleur3",
    "entités":"couleur3",
    "objet":"couleur3",
    "activité":"couleur3",
    "objectif":"couleur3",
    "coordonner":"couleur3",
    "le bord":"couleur4",
    "entre-deux":"couleur3",
    "des deux cercles":"couleur3",
    "360°":"couleur4",
    "L'entre 2":"couleur3",
    "l'entre 2":"couleur3",
    "Traitres":"couleur3",
    "Maux":"couleur3",
    "Multivers":"couleur3",
    "Galaxie":"couleur3",
    "Planète":"couleur3",
    "Biome":"couleur3",
    "Habitat":"couleur3",
    "Virtuel":"couleur2",
    "réalité":"couleur1",
    "un hôte":"couleur3",
    "une autre":"couleur3",
    "habitable":"couleur3",
    "solaire":"couleur3",
    "muses":"couleur3",
    "Troie":"couleur3",
    "Muses":"couleur3",
    "trois":"couleur3",
    "les individus":"couleur3",
};
        function appliquerClassesTexte(element) {
            let ABC = element.innerHTML;
        // Le span
            for (const [mot, classe] of Object.entries(motsClasses2)) {
                const regex = new RegExp(`(?<!\\p{L})${mot}(?!\\p{L})`, "gu");
                ABC = ABC.replace(regex, `<span class="${classe}">${mot}</span>`);
            }
        
            element.innerHTML = ABC;
        }
        // Le id ABC dans body
        const elementABC = document.getElementById("ABC");
        appliquerClassesTexte(elementABC);